FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt .

# Install CPU-only PyTorch FIRST (explicit version)
RUN pip install --no-cache-dir --timeout=1000 \
    torch==2.6.0 \
    torchvision==0.21.0  \
    --index-url https://download.pytorch.org/whl/cpu
   
# Install remaining dependencies
RUN pip install --no-cache-dir --timeout=1000 \ 
    pydantic \
    pydantic-settings \
    "pydantic[email]" \
    python-multipart \
    fastapi \
    uvicorn \
    firebase-admin \
    imagehash \
    pinecone \
    google-generativeai \
    transformers==4.42.0 \
    geopy \
    gtts \
    deep_translator \
    sentence-transformers

# Copy application code
COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]